export const DIALOG_CONTENT = ".Layout-sc-1xcs6mc-0.gYuFlo"
export const GOAL_WIDGET = ".goal_widget"
export const GW_PROGRESS_BAR = ".goal_widget__progress_bar"
export const GW_IMAGE = ".goal_widget__image"
export const GW_METADATA = ".goal_widget__metadata"
export const LEFT_TEXT = ".Layout-sc-1xcs6mc-0.beAYWq"
export const RIGHT_TEXT = ".goal_widget__contributions"
